[package]
name = "rainfall"
version = "0.1.0"
authors = "Cem Geçgel"
edition = "2021"
description = "Thrice to C Transpiler"
readme = "README.md"
repository = "https://github.com/calestialgem/rainfall.rs/"
license = "GPL-3.0-or-later"
